include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SpotifyMusicLyric

SpotifyMusicLyric_FILES = Tweak.xm
SpotifyMusicLyric_CFLAGS = -fobjc-arc
SpotifyMusicLyric_LIBRARIES= mryipc

include $(THEOS_MAKE_PATH)/tweak.mk
