include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SpringBoardExtra

SpringBoardExtra_FILES = CCArtwork.xm MusicBeQuiet.xm QuitAll.xm CleanSpringBoard.xm CompactMediaPlayer.xm DarkLaunchScreen.xm BluetoothLaunch.xm NotifyMusic.xm SpotifyForeground.xm
SpringBoardExtra_PRIVATE_FRAMEWORKS = MediaRemote BulletinBoard
SpringBoardExtra_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk