include $(THEOS)/makefiles/common.mk

TWEAK_NAME = SpringBoardExtra

SpringBoardExtra_FILES = CleanSpringBoard.xm MusicBeQuiet.xm  NotifyMusic.xm
SpringBoardExtra_PRIVATE_FRAMEWORKS = MediaRemote BulletinBoard
SpringBoardExtra_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk