include $(THEOS)/makefiles/common.mk

TWEAK_NAME = QQMusicLyric

QQMusicLyric_FILES = Tweak.xm
QQMusicLyric_CFLAGS = -fobjc-arc
QQMusicLyric_LIBRARIES= rocketbootstrap
QQMusicLyric_PRIVATE_FRAMEWORKS = AppSupport 

include $(THEOS_MAKE_PATH)/tweak.mk
