include $(THEOS)/makefiles/common.mk


TWEAK_NAME = SpringBoardLyric

SpringBoardLyric_FILES = Tweak.xm
SpringBoardLyric_CFLAGS = -fobjc-arc
SpringBoardLyric_LIBRARIES= mryipc
SpringBoardLyric_PRIVATE_FRAMEWORKS = MediaRemote


include $(THEOS_MAKE_PATH)/tweak.mk

