ARCHS = arm64e
TARGET = iphone:latest:13

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = CleanNeteaseMusic

CleanNeteaseMusic_FILES = Tweak.xm
CleanNeteaseMusic_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
